#!/usr/bin/env python

from __future__ import print_function

import os
import select
import sys
import threading

import rospy
from geometry_msgs.msg import Twist

if os.name == 'nt':
    import msvcrt
else:
    import termios
    import tty

MOGUARDER_MAX_LIN_VEL = 0.22
MOGUARDER_MAX_ANG_VEL = 0.75

msg = """
MoGuarder Skid-Steer Keyboard Teleop
------------------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .

i/m/, : forward/backward
j/l : turn left/right in place
u/o : forward arc left/right
. : backward arc right
k or anything else : stop

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%

CTRL-C to quit
"""

e = """
Communications Failed
"""

moveBindings = {
    'i': (1, 0),
    'I': (1, 0),
    'o': (1, -1),
    'j': (0, 1),
    'l': (0, -1),
    'u': (1, 1),
    ',': (-1, 0),
    '.': (-1, 1),
    'm': (-1, 0),
    'M': (-1, 0),
}

speedBindings = {
    'q': (1.1, 1.1),
    'z': (.9, .9),
    'w': (1.1, 1),
    'x': (.9, 1),
    'e': (1, 1.1),
    'c': (1, .9),
}


class PublishThread(threading.Thread):
    def __init__(self, rate):
        super(PublishThread, self).__init__()
        self.publisher = rospy.Publisher('cmd_vel', Twist, queue_size=1)
        self.x = 0.0
        self.th = 0.0
        self.speed = 0.0
        self.turn = 0.0
        self.condition = threading.Condition()
        self.done = False
        self.timeout = None if rate == 0.0 else 1.0 / rate
        self.start()

    def wait_for_subscribers(self):
        i = 0
        while not rospy.is_shutdown() and self.publisher.get_num_connections() == 0:
            if i == 4:
                print("Waiting for subscriber to connect to {}".format(self.publisher.name))
            rospy.sleep(0.5)
            i = (i + 1) % 5
        if rospy.is_shutdown():
            raise Exception("Got shutdown request before subscribers connected")

    def update(self, x, th, speed, turn):
        self.condition.acquire()
        self.x = x
        self.th = th
        self.speed = speed
        self.turn = turn
        self.condition.notify()
        self.condition.release()

    def stop(self):
        self.done = True
        self.update(0, 0, 0, 0)
        self.join()

    def run(self):
        twist = Twist()
        while not self.done:
            self.condition.acquire()
            self.condition.wait(self.timeout)

            twist.linear.x = self.x * self.speed
            twist.linear.y = 0.0
            twist.linear.z = 0.0
            twist.angular.x = 0.0
            twist.angular.y = 0.0
            twist.angular.z = self.th * self.turn

            self.condition.release()
            self.publisher.publish(twist)

        twist.linear.x = 0.0
        twist.linear.y = 0.0
        twist.linear.z = 0.0
        twist.angular.x = 0.0
        twist.angular.y = 0.0
        twist.angular.z = 0.0
        self.publisher.publish(twist)


def getKey(settings, timeout):
    if os.name == 'nt':
        if msvcrt.kbhit():
            if sys.version_info[0] >= 3:
                return msvcrt.getch().decode()
            return msvcrt.getch()
        rospy.sleep(timeout)
        return ''

    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], timeout)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''
    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key


def saveTerminalSettings():
    if os.name == 'nt':
        return None
    return termios.tcgetattr(sys.stdin)


def restoreTerminalSettings(old_settings):
    if os.name != 'nt':
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)


def vels(speed, turn):
    return "currently:\tspeed %.3f\tturn %.3f " % (speed, turn)


def clamp(value, low, high):
    return max(low, min(high, value))


if __name__ == "__main__":
    settings = saveTerminalSettings()

    rospy.init_node('turtlebot3_teleop')

    speed = rospy.get_param("~speed", MOGUARDER_MAX_LIN_VEL)
    turn = rospy.get_param("~turn", MOGUARDER_MAX_ANG_VEL)
    speed_limit = rospy.get_param("~speed_limit", MOGUARDER_MAX_LIN_VEL)
    turn_limit = rospy.get_param("~turn_limit", MOGUARDER_MAX_ANG_VEL)
    repeat_rate = rospy.get_param("~repeat_rate", 10.0)
    key_timeout = rospy.get_param("~key_timeout", 0.4)

    speed = clamp(speed, 0.0, speed_limit)
    turn = clamp(turn, 0.0, turn_limit)

    pub_thread = PublishThread(repeat_rate)

    x = 0
    th = 0
    status = 0

    try:
        pub_thread.wait_for_subscribers()
        pub_thread.update(x, th, speed, turn)

        print(msg)
        print(vels(speed, turn))

        while not rospy.is_shutdown():
            key = getKey(settings, key_timeout)
            if key in moveBindings:
                x = moveBindings[key][0]
                th = moveBindings[key][1]
            elif key in speedBindings:
                speed = clamp(speed * speedBindings[key][0], 0.0, speed_limit)
                turn = clamp(turn * speedBindings[key][1], 0.0, turn_limit)
                print(vels(speed, turn))
                if status == 14:
                    print(msg)
                status = (status + 1) % 15
            else:
                if key == '' and x == 0 and th == 0:
                    continue
                x = 0
                th = 0
                if key == '\x03':
                    break

            pub_thread.update(x, th, speed, turn)

    except Exception:
        print(e)

    finally:
        pub_thread.stop()
        restoreTerminalSettings(settings)
